# Assigment 2

Numpy and Pandas

# Assigment 2 - Numpy Section

## 1.1. Create a random 1D array (lenght 5) using Numpy and print shape, dtype and second value.

## 1.2. Create a random 10x10 matrix using Numpy and print shape, dtype.

## 1.3. Calculate the matrix's total mean, sum, minimum, and maximum.

## 1.4. Calculate the matrix's **first row** mean, sum, minimum, and maximum.

## 1.5. Simulate 100 dice rolls and count how many times each number was rolled.

Hint: Create the simulation using np.random.randint(). Count occurrences with np.bincount().

### 1.1

In [43]:
import numpy as np
array = np.random.random(size=(5))
print(array.shape)
print(array.dtype)
print(array[1])

(5,)
float64
0.02621645413293594

### 1.2

In [44]:
matrix = np.random.random(size=(10, 10))
print(matrix.shape)
print(matrix.dtype)

(10, 10)
float64

### 1.3

In [45]:
print(np.mean(matrix))
print(matrix.sum())
print(matrix.min())
print(matrix.max())

0.48827291357393515
48.82729135739351
0.0072573372610658105
0.9902795778058633

### 1.4

In [50]:
print(np.mean(matrix[0]))
print(matrix[0].sum())
print(matrix[0].min())
print(matrix[0].max())

0.45438119841571395
4.54381198415714
0.08024884787830111
0.9021479029788141

### 1.5

In [62]:
rolls = np.random.randint(1,7, size=100)
counts = np.bincount(rolls)

print("The number of times each number rolled on a 100 dice rolls")
for num in range(1, 7):
    print(f"{num}: {counts[num]}")

The number of times each number rolled on a 100 dice rolls
1: 19
2: 15
3: 19
4: 22
5: 15
6: 10

# Assigment 2 - Pandas Section - Wildlife Accidents

## 2.1. Determine in which month the highest number of wildlife accidents occur. Is there a difference between months?

Group the data by month and count the number of accidents. Print also with the results sorted descending. Also comment on the results.

## 2.2. Create a cross-tabulation table showing how wildlife accidents are distributed across species and regions.

Using the wildlife accidents DataFrame (riista_df), create a cross-tabulation where rows represent wildlife species (riistalajiNimi), columns represent regions (maakuntaNimi).

## 2.3. Convert the "eventTime" column to Pandas datetime format and analyze which hours of day are the most dangerous for wildlife accidents.

Hint: Create additional columns for the day of the week and the hour of day using the pd.to_datetime() function

### 2.1

In [35]:
import pandas as pd

In [36]:
df = pd.read_csv("koeti_riista_tau_001_fi.csv",  encoding="latin1")
df.head(3)

,id,tapahtumaAika,vuosi,kuukausi,x,y,kunta,kuntaNimi,maakunta,maakuntaNimi,tielaji,tielajis,tieNumero,tieYllapito,tieYllapitoNimi,riistalaji,riistalajiNimi
0,1,2017-12-10T16:55:00.000+02:00,2017,12,278773.659,6980877.550,743,Seinäjoki,14,Etelä-Pohjanmaa,3,Valtatie,18.0,1.0,Valtio,47507,Metsäkauris
1,2,2017-09-03T13:00:00.000+03:00,2017,9,397501.008,7503083.730,261,Kittilä,19,Lappi,4,Kantatie,80.0,1.0,Valtio,47503,Hirvi
2,3,2017-09-18T07:00:00.000+03:00,2017,9,418353.841,7514104.657,261,Kittilä,19,Lappi,6,Muu maantie,9552.0,1.0,Valtio,47503,Hirvi

In [37]:
monthly_count = df.groupby("kuukausi").size()
monthly_count_desc = monthly_count.sort_values(ascending=False)
print(monthly_count_desc)

kuukausi
11    10962
10     8467
12     6382
5      6301
9      5995
6      5551
7      4516
8      4450
1      4110
4      3007
2      2194
3      2007
dtype: int64

Eniten riistaonnettomuuksia tapahtuu marras-, loka- ja joulukuussa. Vähiten puolestaan tammi- ja huhtikuun välisenä aikana.

### 2.2

In [ ]:
pd.crosstab(df["riistalajiNimi"], df["maakuntaNimi"])

maakuntaNimi,Etelä-Karjala,Etelä-Pohjanmaa,Etelä-Savo,Kainuu,Kanta-Häme,Keski-Pohjanmaa,Keski-Suomi,Kymenlaakso,Lappi,Pirkanmaa,Pohjanmaa,Pohjois-Karjala,Pohjois-Pohjanmaa,Pohjois-Savo,Päijät-Häme,Satakunta,Uusimaa,Varsinais-Suomi
riistalajiNimi,,,,,,,,,,,,,,,,,,
Hirvi,291,514,514,319,309,163,763,272,674,693,569,587,861,550,253,492,798,571
Kuusipeura,0,0,0,0,13,0,0,0,0,0,0,0,1,0,0,20,52,1
Metsäkauris,216,744,243,106,1601,196,1098,474,513,2797,1111,157,697,375,1044,2562,4020,4512
Metsäpeura,0,57,0,68,0,123,13,0,0,1,5,0,55,0,0,3,0,0
Valkohäntäpeura,66,303,185,0,4004,10,369,117,0,4990,334,0,18,55,657,3336,7351,9908
Villisika,17,1,7,1,7,0,10,30,0,12,2,11,3,0,20,3,39,5